name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/project-nevareth/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
    - name: Build AutoServiceGenerator with dotnet
      run: dotnet build NetX.AutoServiceGenerator\NetX.AutoServiceGenerator.csproj --configuration Release --output ./npkg
    - name: Build AutoServiceGenerator.Definitions with dotnet
      run: dotnet build NetX.AutoServiceGenerator.Definitions\NetX.AutoServiceGenerator.Definitions.csproj --configuration Release --output ./npkg
    - name: Publish
      run: dotnet nuget push "npkg/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/project-nevareth/index.json --skip-duplicate
