name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
    - name: Add GitHub Packages Source
      run: dotnet nuget add source https://nuget.pkg.github.com/project-nevareth/index.json -n github -u ${{secrets.MEU_USER}} -p ${{secrets.MEU_TOKEN}} --store-password-in-clear-text
    - name: Build with dotnet
      run: dotnet build --configuration Release --output ./npkg
    - name: Publish
      run: dotnet nuget push "npkg/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/project-nevareth/index.json --skip-duplicate
