name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Add GitHub Packages Source
      run: dotnet nuget add source https://nuget.pkg.github.com/project-nevareth/index.json -n github -u ${{secrets.MEU_USER}} -p ${{secrets.MEU_TOKEN}} --store-password-in-clear-text
    - name: Build with dotnet
      run: dotnet build --configuration Release --output ./npkg
    - name: Publish
      run: dotnet nuget push "npkg/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/project-nevareth/index.json --skip-duplicate
